name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: üéâ iOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # 1. –ü–æ–ª–Ω–∞—è –æ—á–∏—Å—Ç–∫–∞ Flutter
      - name: Clean Flutter
        run: flutter clean

      # 2. –£—Å—Ç–∞–Ω–æ–≤–∫–∞ –∑–∞–≤–∏—Å–∏–º–æ—Å—Ç–µ–π Flutter (—Å–æ–∑–¥–∞—ë—Ç Generated.xcconfig)
      - name: Get Flutter packages
        run: flutter pub get

      # 3. –û—á–∏—Å—Ç–∫–∞ Pods –∏ —É—Å—Ç–∞–Ω–æ–≤–∫–∞ –∑–∞–Ω–æ–≤–æ
      - name: Clean iOS Pods
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install
          cd ..

      # 4. –°–±–æ—Ä–∫–∞ iOS
      - name: Build iOS release
        run: flutter build ios --release --no-codesign

      # 5. –°–æ–∑–¥–∞–Ω–∏–µ Payload
      - name: Create Payload folder
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move Runner.app into Payload
        run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # 6. –ê—Ä—Ö–∏–≤–∞—Ü–∏—è –≤ IPA
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # 7. –ó–∞–≥—Ä—É–∑–∫–∞ IPA –≤ —Ä–µ–ª–∏–∑
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
